"""admin apply c

Revision ID: 0105fc1b00d0
Revises: bf0b4ad490f4
Create Date: 2021-04-30 17:30:57.371558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0105fc1b00d0'
down_revision = 'bf0b4ad490f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_apply_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_account', sa.String(length=127), nullable=True))
        batch_op.add_column(sa.Column('basic_account_address', sa.String(length=127), nullable=True))
        batch_op.add_column(sa.Column('basic_account_name', sa.String(length=127), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_apply_file', schema=None) as batch_op:
        batch_op.drop_column('basic_account_name')
        batch_op.drop_column('basic_account_address')
        batch_op.drop_column('basic_account')

    # ### end Alembic commands ###
