"""[feat] info

Revision ID: 03c64d352ed9
Revises: c40a76afc676
Create Date: 2021-03-31 11:25:58.385424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c64d352ed9'
down_revision = 'c40a76afc676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=31), nullable=True))
        batch_op.add_column(sa.Column('sub_file', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=127), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_detail', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('summary')
        batch_op.drop_column('sub_file')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
