"""hedge comment

Revision ID: 0596a9cade89
Revises: e279b9d49d79
Create Date: 2021-01-13 09:43:26.869740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0596a9cade89'
down_revision = 'e279b9d49d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hedge_comments',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.CHAR(length=16), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['hedge_fund_info.fund_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hedge_fund_info', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hedge_fund_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', mysql.VARCHAR(length=511), nullable=True))

    op.drop_table('hedge_comments')
    # ### end Alembic commands ###
