"""managements information

Revision ID: 0edaf08f0556
Revises: 1a3a34d50fc5
Create Date: 2021-03-12 15:03:53.798868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edaf08f0556'
down_revision = '1a3a34d50fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_investors',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('manager_id', sa.String(length=16), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('manager_id', 'number')
    )
    op.create_table('management_related_parties',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('manager_id', sa.String(length=16), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('related_manager_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('invest_type', sa.String(length=32), nullable=True),
    sa.Column('register_no', sa.String(length=8), nullable=True),
    sa.Column('organization_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('manager_id', 'number')
    )
    op.create_table('management_seniors',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.String(length=16), nullable=True),
    sa.Column('job_title', sa.String(length=64), nullable=True),
    sa.Column('senior_name', sa.String(length=32), nullable=True),
    sa.Column('has_qualification', sa.String(length=1), nullable=True),
    sa.Column('qualification_source', sa.String(length=8), nullable=True),
    sa.Column('job_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('management_seniors')
    op.drop_table('management_related_parties')
    op.drop_table('management_investors')
    # ### end Alembic commands ###
