"""fof position

Revision ID: 12e932ff7b8a
Revises: 525d2f7408db
Create Date: 2021-01-13 17:31:30.540403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12e932ff7b8a'
down_revision = '525d2f7408db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fof_position',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('fof_id', sa.CHAR(length=16), nullable=False),
    sa.Column('datetime', sa.DATE(), nullable=False),
    sa.Column('position', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('fof_id', 'datetime')
    )
    with op.batch_alter_table('hedge_fund_info', schema=None) as batch_op:
        batch_op.drop_column('fund_scale')
        batch_op.drop_column('fund_manager')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hedge_fund_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_manager', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('fund_scale', mysql.DOUBLE(asdecimal=True), nullable=True))

    op.drop_table('fof_position')
    # ### end Alembic commands ###
