"""fof nav

Revision ID: 1a31207385e2
Revises: dba91f0c5df5
Create Date: 2021-01-12 13:48:47.765370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a31207385e2'
down_revision = 'dba91f0c5df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fof_nav',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('fof_id', sa.CHAR(length=16), nullable=False),
    sa.Column('datetime', sa.DATE(), nullable=False),
    sa.Column('nav', mysql.DOUBLE(), nullable=False),
    sa.PrimaryKeyConstraint('fof_id', 'datetime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fof_nav')
    # ### end Alembic commands ###
