"""manager info struct

Revision ID: 1a3a34d50fc5
Revises: 856a35c65687
Create Date: 2021-03-12 13:14:18.024563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3a34d50fc5'
down_revision = '856a35c65687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_manager_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('legal_person', sa.String(length=31), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_manager_info', schema=None) as batch_op:
        batch_op.drop_column('legal_person')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
