"""custom index

Revision ID: 1a3f2d032326
Revises: b06b9e74f2e0
Create Date: 2021-01-14 12:45:44.527950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a3f2d032326'
down_revision = 'b06b9e74f2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_index',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('recent_1m_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_3m_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_6m_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_y1_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_y3_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_y5_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('mdd', mysql.DOUBLE(), nullable=True),
    sa.Column('sharpe', mysql.DOUBLE(), nullable=True),
    sa.Column('last_unit_nav', mysql.DOUBLE(), nullable=True),
    sa.Column('annualized_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('annualized_vol', mysql.DOUBLE(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_index_nav',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.Date(), nullable=True),
    sa.Column('nav', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_index_nav')
    op.drop_table('custom_index')
    # ### end Alembic commands ###
