"""template name

Revision ID: 1ae7861be34c
Revises: 1b53fc80f467
Create Date: 2021-04-26 11:46:09.253102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae7861be34c'
down_revision = '1b53fc80f467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_template', schema=None) as batch_op:
        batch_op.drop_column('template_name')

    # ### end Alembic commands ###
