"""production template

Revision ID: 1b53fc80f467
Revises: 654f0dfb2bf4
Create Date: 2021-04-25 15:16:44.814699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b53fc80f467'
down_revision = '654f0dfb2bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_template',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fof_id', sa.String(length=16), nullable=True),
    sa.Column('manager_id', sa.String(length=32), nullable=True),
    sa.Column('template_status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_template', schema=None) as batch_op:
        batch_op.drop_column('signed')

    op.drop_table('production_template')
    # ### end Alembic commands ###
