"""hedge info nav

Revision ID: 200a4e83c6be
Revises: 1a3f2d032326
Create Date: 2021-01-15 10:50:49.118399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '200a4e83c6be'
down_revision = '1a3f2d032326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hedge_fund_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acc_unit_value', mysql.DOUBLE(), nullable=True))
        batch_op.add_column(sa.Column('net_asset_value', mysql.DOUBLE(), nullable=True))
        batch_op.add_column(sa.Column('v_net_value', mysql.DOUBLE(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hedge_fund_info', schema=None) as batch_op:
        batch_op.drop_column('v_net_value')
        batch_op.drop_column('net_asset_value')
        batch_op.drop_column('acc_unit_value')

    # ### end Alembic commands ###
