"""real name

Revision ID: 2334e7cbd706
Revises: 72d74d8cd945
Create Date: 2021-04-27 16:01:25.182422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2334e7cbd706'
down_revision = '72d74d8cd945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor_certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_name_bank_card', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('real_name_image_url_key', sa.String(length=128), nullable=True))
        batch_op.drop_column('face_image_url_key')
        batch_op.drop_column('face_image_verify_time')

    with op.batch_alter_table('investor_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_name_bank_card', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('real_name_image_url_key', sa.String(length=128), nullable=True))
        batch_op.drop_column('face_image_url_key')
        batch_op.drop_column('face_image_verify_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_image_verify_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('face_image_url_key', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('real_name_image_url_key')
        batch_op.drop_column('real_name_bank_card')

    with op.batch_alter_table('investor_certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_image_verify_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('face_image_url_key', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('real_name_image_url_key')
        batch_op.drop_column('real_name_bank_card')

    # ### end Alembic commands ###
