"""init

Revision ID: 3b23ec0f0c2a
Revises: 
Create Date: 2021-01-19 15:31:31.517008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b23ec0f0c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha_img',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.CHAR(length=64), nullable=True),
    sa.Column('value', sa.CHAR(length=64), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_index',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('recent_1m_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_3m_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_6m_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_y1_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_y3_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('recent_y5_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('mdd', mysql.DOUBLE(), nullable=True),
    sa.Column('sharpe', mysql.DOUBLE(), nullable=True),
    sa.Column('last_unit_nav', mysql.DOUBLE(), nullable=True),
    sa.Column('annualized_ret', mysql.DOUBLE(), nullable=True),
    sa.Column('annualized_vol', mysql.DOUBLE(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_index_nav',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.Date(), nullable=True),
    sa.Column('nav', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hedge_comments',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', mysql.CHAR(length=16), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobile_code',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=True),
    sa.Column('value', sa.CHAR(length=64), nullable=True),
    sa.Column('action', sa.CHAR(length=31), nullable=True),
    sa.Column('try_times', sa.Integer(), nullable=True),
    sa.Column('success_times', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_login',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(length=31), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=128), nullable=True),
    sa.Column('site', sa.String(length=256), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('sign_date', sa.String(length=20), nullable=True),
    sa.Column('sponsor', sa.String(length=20), nullable=True),
    sa.Column('investor_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('we_chat_token',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.CHAR(length=255), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('token_type', sa.CHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('refresh_key', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_we_chat',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('union_id', sa.CHAR(length=128), nullable=True),
    sa.Column('open_id', sa.CHAR(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_we_chat')
    op.drop_table('tokens')
    op.drop_table('we_chat_token')
    op.drop_table('users')
    op.drop_table('user_login')
    op.drop_table('mobile_code')
    op.drop_table('hedge_comments')
    op.drop_table('custom_index_nav')
    op.drop_table('custom_index')
    op.drop_table('captcha_img')
    # ### end Alembic commands ###
