"""fof asset trade type

Revision ID: 525d2f7408db
Revises: 0596a9cade89
Create Date: 2021-01-13 15:14:05.967865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525d2f7408db'
down_revision = '0596a9cade89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fof_asset_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade_type', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fof_asset_allocation', schema=None) as batch_op:
        batch_op.drop_column('trade_type')

    # ### end Alembic commands ###
