"""message

Revision ID: 587b50b711a7
Revises: 0e82dd4cc89f
Create Date: 2021-03-22 16:22:28.355310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587b50b711a7'
down_revision = '0e82dd4cc89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_task_sub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('err_msg', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('task_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_task_sub', schema=None) as batch_op:
        batch_op.drop_column('task_status')
        batch_op.drop_column('err_msg')

    # ### end Alembic commands ###
