"""[feat] info pro

Revision ID: 599c0e0a6154
Revises: 03c64d352ed9
Create Date: 2021-03-31 15:01:33.281317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599c0e0a6154'
down_revision = '03c64d352ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_to_production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_to_production', schema=None) as batch_op:
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
