"""email code

Revision ID: 654f0dfb2bf4
Revises: c267c9aebad3
Create Date: 2021-04-22 17:56:02.358851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654f0dfb2bf4'
down_revision = 'c267c9aebad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha_email',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=127), nullable=True),
    sa.Column('value', sa.CHAR(length=64), nullable=True),
    sa.Column('action', sa.CHAR(length=31), nullable=True),
    sa.Column('try_times', sa.Integer(), nullable=True),
    sa.Column('success_times', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_manager_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=127), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=11), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_manager_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mobile')
        batch_op.drop_column('email')

    op.drop_table('captcha_email')
    # ### end Alembic commands ###
