"""investor id

Revision ID: 6df7d149ab0f
Revises: 2849672e6485
Create Date: 2021-01-15 19:03:09.615781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df7d149ab0f'
down_revision = '2849672e6485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_positions', schema=None) as batch_op:
        batch_op.drop_column('asset_type')

    # ### end Alembic commands ###
