"""fof calc status

Revision ID: 72d74d8cd945
Revises: 1ae7861be34c
Create Date: 2021-04-26 15:25:57.512594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d74d8cd945'
down_revision = '1ae7861be34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fof_calc_status',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fof_id', sa.CHAR(length=16), nullable=True),
    sa.Column('manager_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('failed_reason', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fof_calc_status')
    # ### end Alembic commands ###
