"""nav mail setting

Revision ID: 74766296cff9
Revises: a75bce6c4ace
Create Date: 2021-04-01 15:31:56.974490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74766296cff9'
down_revision = 'a75bce6c4ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_nav_email',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.String(length=32), nullable=True),
    sa.Column('server', sa.String(length=127), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=127), nullable=True),
    sa.Column('password', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('manager_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager_nav_email')
    # ### end Alembic commands ###
