"""user wx

Revision ID: 751b0fa8e289
Revises: de21ad7becb2
Create Date: 2021-01-27 13:32:49.044893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751b0fa8e289'
down_revision = 'de21ad7becb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_wx', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_wx')

    # ### end Alembic commands ###
