"""managements

Revision ID: 856a35c65687
Revises: 900319465ac3
Create Date: 2021-03-12 11:11:22.833078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856a35c65687'
down_revision = '900319465ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_funds',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('fund_id', sa.String(length=16), nullable=False),
    sa.Column('fund_name', sa.String(length=128), nullable=True),
    sa.Column('fund_no', sa.String(length=6), nullable=True),
    sa.Column('establish_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_stage', sa.String(length=16), nullable=True),
    sa.Column('fund_type', sa.String(length=16), nullable=True),
    sa.Column('currency_type', sa.String(length=16), nullable=True),
    sa.Column('management_type', sa.String(length=16), nullable=True),
    sa.Column('custodian_name', sa.String(length=128), nullable=True),
    sa.Column('fund_status', sa.String(length=16), nullable=True),
    sa.Column('special_reminder', sa.Text(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('manager_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('fund_id')
    )
    op.create_table('managements',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('manager_id', sa.String(length=16), nullable=False),
    sa.Column('manager_name', sa.String(length=128), nullable=True),
    sa.Column('person_name', sa.String(length=32), nullable=True),
    sa.Column('invest_type', sa.String(length=32), nullable=True),
    sa.Column('register_no', sa.String(length=8), nullable=True),
    sa.Column('member_type', sa.String(length=8), nullable=True),
    sa.Column('has_special_tips', sa.Boolean(), nullable=True),
    sa.Column('has_credit_tips', sa.Boolean(), nullable=True),
    sa.Column('establish_date', sa.Date(), nullable=True),
    sa.Column('register_date', sa.Date(), nullable=True),
    sa.Column('fund_count', sa.Integer(), nullable=True),
    sa.Column('office_province', sa.String(length=16), nullable=True),
    sa.Column('office_city', sa.String(length=16), nullable=True),
    sa.Column('office_address', sa.String(length=128), nullable=True),
    sa.Column('register_province', sa.String(length=16), nullable=True),
    sa.Column('register_city', sa.String(length=16), nullable=True),
    sa.Column('register_address', sa.String(length=128), nullable=True),
    sa.Column('manager_name_en', sa.String(length=128), nullable=True),
    sa.Column('organization_code', sa.String(length=32), nullable=True),
    sa.Column('register_capital', sa.Float(), nullable=True),
    sa.Column('register_currency', sa.String(length=8), nullable=True),
    sa.Column('payment_capital', sa.Float(), nullable=True),
    sa.Column('payment_currency', sa.String(length=8), nullable=True),
    sa.Column('payment_ratio', sa.Float(), nullable=True),
    sa.Column('enterprise_nature', sa.String(length=16), nullable=True),
    sa.Column('business_type', sa.JSON(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('practitioner_count', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('manager_size', sa.String(length=16), nullable=True),
    sa.Column('is_member', sa.String(length=1), nullable=True),
    sa.Column('member_representative', sa.String(length=32), nullable=True),
    sa.Column('current_member_type', sa.String(length=8), nullable=True),
    sa.Column('member_time', sa.Date(), nullable=True),
    sa.Column('legal_opinion_status', sa.String(length=8), nullable=True),
    sa.Column('law_firm_name', sa.String(length=32), nullable=True),
    sa.Column('lawyer_name', sa.String(length=32), nullable=True),
    sa.Column('controller_name', sa.String(length=128), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('fund_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('manager_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('managements')
    op.drop_table('management_funds')
    # ### end Alembic commands ###
