"""manager logos

Revision ID: a75bce6c4ace
Revises: 599c0e0a6154
Create Date: 2021-04-01 10:10:35.287669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75bce6c4ace'
down_revision = '599c0e0a6154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fof_logos',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.String(length=32), nullable=True),
    sa.Column('fof_id', sa.String(length=16), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_manager_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_manager_info', schema=None) as batch_op:
        batch_op.drop_column('logo')

    op.drop_table('fof_logos')
    # ### end Alembic commands ###
