"""fof user

Revision ID: b06b9e74f2e0
Revises: 12e932ff7b8a
Create Date: 2021-01-14 10:12:55.523156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06b9e74f2e0'
down_revision = '12e932ff7b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sign_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sponsor', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sponsor')
        batch_op.drop_column('sign_date')
        batch_op.drop_column('name')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
