"""user struct

Revision ID: b35c93c18505
Revises: 751b0fa8e289
Create Date: 2021-02-01 16:08:41.859559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35c93c18505'
down_revision = '751b0fa8e289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('contact_mobile', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.String(length=31), nullable=True))
        batch_op.add_column(sa.Column('ins_code', sa.String(length=31), nullable=True))
        batch_op.add_column(sa.Column('ins_name', sa.String(length=63), nullable=True))
        batch_op.add_column(sa.Column('is_institution', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_institution')
        batch_op.drop_column('ins_name')
        batch_op.drop_column('ins_code')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('contact_mobile')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
