"""message

Revision ID: ba9dd5afd7b1
Revises: c1630063aca5
Create Date: 2021-03-22 16:12:53.331702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9dd5afd7b1'
down_revision = 'c1630063aca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_logs',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('retval', sa.Text(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('task_status', sa.Boolean(), nullable=True),
    sa.Column('exc', sa.Text(), nullable=True),
    sa.Column('einfo', sa.Text(), nullable=True),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('kwargs', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('time_done', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('celery_task_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_celery_task_logs_task_id'), ['task_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_celery_task_logs_task_id'))

    op.drop_table('celery_task_logs')
    # ### end Alembic commands ###
