"""production template

Revision ID: bf0b4ad490f4
Revises: cba074cc24aa
Create Date: 2021-04-29 10:43:27.646682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf0b4ad490f4'
down_revision = 'cba074cc24aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_template',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('fof_id', sa.String(length=16), nullable=True),
    sa.Column('manager_id', sa.String(length=32), nullable=True),
    sa.Column('template_type', sa.String(length=16), nullable=True),
    sa.Column('template_name', sa.String(length=128), nullable=True),
    sa.Column('template_url_key', sa.String(length=128), nullable=True),
    sa.Column('signed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    with op.batch_alter_table('production_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_template_fof_id'), ['fof_id'], unique=False)

    with op.batch_alter_table('contract_template', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_template_fof_id')

    op.drop_table('contract_template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_template',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('template_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fof_id', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('manager_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('template_type', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('template_url_key', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('signed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('template_name', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('template_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('contract_template', schema=None) as batch_op:
        batch_op.create_index('ix_contract_template_fof_id', ['fof_id'], unique=False)

    with op.batch_alter_table('production_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_template_fof_id'))

    op.drop_table('production_template')
    # ### end Alembic commands ###
