"""contract template

Revision ID: c1630063aca5
Revises: 3c4c965beace
Create Date: 2021-03-17 17:32:04.056382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1630063aca5'
down_revision = '3c4c965beace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_template',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('fof_id', sa.String(length=16), nullable=True),
    sa.Column('manager_id', sa.String(length=32), nullable=True),
    sa.Column('template_type', sa.String(length=16), nullable=True),
    sa.Column('template_url_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    with op.batch_alter_table('contract_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_template_fof_id'), ['fof_id'], unique=False)

    with op.batch_alter_table('investor_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor_information', schema=None) as batch_op:
        batch_op.drop_column('secret')

    with op.batch_alter_table('contract_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_template_fof_id'))

    op.drop_table('contract_template')
    # ### end Alembic commands ###
