"""apply status

Revision ID: c267c9aebad3
Revises: 64f600dd153e
Create Date: 2021-04-22 12:05:28.023758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c267c9aebad3'
down_revision = '64f600dd153e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_apply_status',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apply_id', sa.Integer(), nullable=True),
    sa.Column('manager_cred', sa.BOOLEAN(), nullable=True),
    sa.Column('lp_cred', sa.BOOLEAN(), nullable=True),
    sa.Column('admin_cred', sa.BOOLEAN(), nullable=True),
    sa.Column('service_cred', sa.BOOLEAN(), nullable=True),
    sa.Column('hf_success', sa.BOOLEAN(), nullable=True),
    sa.Column('sign_status', sa.Integer(), nullable=True),
    sa.Column('failed_reason', sa.String(length=127), nullable=True),
    sa.ForeignKeyConstraint(['apply_id'], ['admin_apply_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_apply_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_cred_file', sa.String(length=127), nullable=True))
        batch_op.add_column(sa.Column('admin_cred_type', sa.String(length=31), nullable=True))
        batch_op.add_column(sa.Column('pu_yuan_auth_file', sa.String(length=127), nullable=True))
        batch_op.add_column(sa.Column('service_file', sa.String(length=127), nullable=True))
        batch_op.add_column(sa.Column('sign_stage', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_unit_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_time', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_unit_map', schema=None) as batch_op:
        batch_op.drop_column('latest_time')

    with op.batch_alter_table('admin_apply_file', schema=None) as batch_op:
        batch_op.drop_column('sign_stage')
        batch_op.drop_column('service_file')
        batch_op.drop_column('pu_yuan_auth_file')
        batch_op.drop_column('admin_cred_type')
        batch_op.drop_column('admin_cred_file')

    op.drop_table('admin_apply_status')
    # ### end Alembic commands ###
