"""wx template column

Revision ID: c40a76afc676
Revises: d9da63806f26
Create Date: 2021-03-29 10:17:52.402913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40a76afc676'
down_revision = 'd9da63806f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager_wx_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_template_id', sa.String(length=127), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager_wx_account', schema=None) as batch_op:
        batch_op.drop_column('nav_template_id')

    # ### end Alembic commands ###
