"""info

Revision ID: c98e11312db9
Revises: 821bd2574420
Create Date: 2021-03-04 14:22:18.786808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98e11312db9'
down_revision = '821bd2574420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_detail',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=63), nullable=True),
    sa.Column('info_type', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Integer(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('is_effected', sa.BOOLEAN(), nullable=True),
    sa.Column('effect_time', sa.DATETIME(), nullable=True),
    sa.Column('effect_user_name', sa.String(63), nullable=True),
    sa.Column('create_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_templates',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_to_production',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('info_id', sa.Integer(), nullable=True),
    sa.Column('fof_id', sa.CHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager_info',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager_info')
    op.drop_table('info_to_production')
    op.drop_table('info_templates')
    op.drop_table('info_detail')
    # ### end Alembic commands ###
