"""fof nav

Revision ID: cc0abd767bcd
Revises: 1a31207385e2
Create Date: 2021-01-12 14:13:42.712598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc0abd767bcd'
down_revision = '1a31207385e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hedge_fund_info',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('fund_id', sa.CHAR(length=16), nullable=False),
    sa.Column('fund_name', sa.TEXT(), nullable=False),
    sa.Column('manager_id', sa.CHAR(length=16), nullable=False),
    sa.Column('water_line', mysql.DOUBLE(), nullable=False),
    sa.Column('incentive_fee_mode', sa.TEXT(), nullable=False),
    sa.Column('incentive_fee_ratio', mysql.DOUBLE(), nullable=False),
    sa.Column('v_nav_decimals', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('fund_id')
    )
    op.create_table('hedge_fund_nav',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('fund_id', sa.CHAR(length=16), nullable=False),
    sa.Column('datetime', sa.DATE(), nullable=False),
    sa.Column('insert_time', sa.DATETIME(), nullable=False),
    sa.Column('calc_date', sa.DATE(), nullable=True),
    sa.Column('net_asset_value', mysql.DOUBLE(), nullable=False),
    sa.Column('acc_unit_value', mysql.DOUBLE(), nullable=True),
    sa.Column('v_net_value', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('fund_id', 'datetime', 'insert_time')
    )
    with op.batch_alter_table('hedge_fund_nav', schema=None) as batch_op:
        batch_op.create_index('idx_hedge_fund_nav_datetime', ['datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hedge_fund_nav', schema=None) as batch_op:
        batch_op.drop_index('idx_hedge_fund_nav_datetime')

    op.drop_table('hedge_fund_nav')
    op.drop_table('hedge_fund_info')
    # ### end Alembic commands ###
