"""investor position

Revision ID: d533ee3ade30
Revises: 200a4e83c6be
Create Date: 2021-01-15 18:33:39.839564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd533ee3ade30'
down_revision = '200a4e83c6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_positions',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('fof_id', sa.String(length=16), nullable=True),
    sa.Column('amount', mysql.DOUBLE(), nullable=True),
    sa.Column('shares', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_positions')
    # ### end Alembic commands ###
