"""fof tag

Revision ID: d81241fc2c84
Revises: 348905f4a43a
Create Date: 2021-04-02 17:51:45.060008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81241fc2c84'
down_revision = '348905f4a43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fof_tags',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=16), nullable=True),
    sa.Column('fof_id', sa.String(length=32), nullable=True),
    sa.Column('manager_id', sa.String(length=32), nullable=True),
    sa.Column('add_user_id', sa.Integer(), nullable=True),
    sa.Column('del_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fof_tags')
    # ### end Alembic commands ###
