"""message add col

Revision ID: da6216481fdd
Revises: d3800d7babaa
Create Date: 2021-03-24 15:30:47.606651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6216481fdd'
down_revision = 'd3800d7babaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_task_sub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_from', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_task_sub', schema=None) as batch_op:
        batch_op.drop_column('task_from')

    # ### end Alembic commands ###
