"""init

Revision ID: dba91f0c5df5
Revises: 
Create Date: 2021-01-12 11:57:35.826993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba91f0c5df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha_img',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.CHAR(length=64), nullable=True),
    sa.Column('value', sa.CHAR(length=64), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fof_asset_allocation',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fof_id', sa.CHAR(length=16), nullable=False),
    sa.Column('datetime', sa.DATE(), nullable=False),
    sa.Column('fund_id', sa.CHAR(length=16), nullable=False),
    sa.Column('asset_type', sa.String(length=31), nullable=False),
    sa.Column('amount', mysql.DOUBLE(), nullable=True),
    sa.Column('share', mysql.DOUBLE(), nullable=True),
    sa.Column('status', sa.String(length=31), nullable=False),
    sa.Column('confirmed_date', sa.DATE(), nullable=True),
    sa.Column('unit_total', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'fof_id', 'datetime', 'fund_id')
    )
    op.create_table('fof_info',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('fof_id', sa.CHAR(length=16), nullable=False),
    sa.Column('datetime', sa.CHAR(length=16), nullable=False),
    sa.Column('fof_name', sa.TEXT(), nullable=False),
    sa.Column('admin', sa.TEXT(), nullable=False),
    sa.Column('established_date', sa.DATE(), nullable=False),
    sa.Column('fof_status', sa.TEXT(), nullable=False),
    sa.Column('subscription_fee', mysql.DOUBLE(), nullable=False),
    sa.Column('redemption_fee', mysql.DOUBLE(), nullable=False),
    sa.Column('management_fee', mysql.DOUBLE(), nullable=False),
    sa.Column('custodian_fee', mysql.DOUBLE(), nullable=False),
    sa.Column('administrative_fee', mysql.DOUBLE(), nullable=False),
    sa.Column('lock_up_period', sa.TEXT(), nullable=False),
    sa.Column('incentive_fee_mode', sa.TEXT(), nullable=False),
    sa.Column('incentive_fee', sa.TEXT(), nullable=False),
    sa.Column('current_deposit_rate', mysql.DOUBLE(), nullable=False),
    sa.Column('initial_raised_fv', mysql.DOUBLE(), nullable=False),
    sa.Column('initial_net_value', mysql.DOUBLE(), nullable=False),
    sa.PrimaryKeyConstraint('fof_id', 'datetime')
    )
    op.create_table('fof_manually',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('fof_id', sa.CHAR(length=16), nullable=False),
    sa.Column('datetime', sa.DATE(), nullable=False),
    sa.Column('fee_transfer', mysql.DOUBLE(), nullable=True),
    sa.Column('cd_interest_transfer', mysql.DOUBLE(), nullable=True),
    sa.Column('other_fees', mysql.DOUBLE(), nullable=True),
    sa.Column('management_fee_error', mysql.DOUBLE(), nullable=True),
    sa.Column('custodian_fee_error', mysql.DOUBLE(), nullable=True),
    sa.Column('admin_service_fee_error', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('fof_id', 'datetime')
    )
    op.create_table('fof_scale_alteration',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fof_id', sa.CHAR(length=16), nullable=False),
    sa.Column('datetime', sa.DATE(), nullable=False),
    sa.Column('confirmed_date', sa.DATE(), nullable=True),
    sa.Column('deposited_date', sa.DATE(), nullable=True),
    sa.Column('amount', mysql.DOUBLE(), nullable=True),
    sa.Column('share', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'fof_id', 'datetime')
    )
    op.create_table('mobile_code',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=True),
    sa.Column('value', sa.CHAR(length=64), nullable=True),
    sa.Column('action', sa.CHAR(length=31), nullable=True),
    sa.Column('try_times', sa.Integer(), nullable=True),
    sa.Column('success_times', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_login',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(length=31), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=128), nullable=True),
    sa.Column('site', sa.String(length=256), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('refresh_key', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('users')
    op.drop_table('user_login')
    op.drop_table('mobile_code')
    op.drop_table('fof_scale_alteration')
    op.drop_table('fof_manually')
    op.drop_table('fof_info')
    op.drop_table('fof_asset_allocation')
    op.drop_table('captcha_img')
    # ### end Alembic commands ###
