"""investor credentials

Revision ID: de21ad7becb2
Revises: 3b23ec0f0c2a
Create Date: 2021-01-25 16:34:54.780472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de21ad7becb2'
down_revision = '3b23ec0f0c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_token',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.CHAR(length=255), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('token_type', sa.CHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('we_chat_token')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cred', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cred_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cred_type')
        batch_op.drop_column('cred')

    op.create_table('we_chat_token',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('key', mysql.CHAR(length=255), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('token_type', mysql.CHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('wechat_token')
    # ### end Alembic commands ###
