"""investor id

Revision ID: df5ee6b7837c
Revises: 6df7d149ab0f
Create Date: 2021-01-18 09:52:20.122388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5ee6b7837c'
down_revision = '6df7d149ab0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fof_asset_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investor_id', sa.CHAR(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fof_asset_allocation', schema=None) as batch_op:
        batch_op.drop_column('investor_id')

    # ### end Alembic commands ###
