"""message

Revision ID: e1b2a107e676
Revises: 587b50b711a7
Create Date: 2021-03-22 18:02:51.367826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b2a107e676'
down_revision = '587b50b711a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_wx_account',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('manager_id', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.String(length=127), nullable=True),
    sa.Column('app_sec', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('manager_id')
    )
    with op.batch_alter_table('wechat_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['manager_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('manager_id')

    op.drop_table('manager_wx_account')
    # ### end Alembic commands ###
