"""mobile

Revision ID: e279b9d49d79
Revises: cc0abd767bcd
Create Date: 2021-01-12 17:54:20.763227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e279b9d49d79'
down_revision = 'cc0abd767bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hedge_fund_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=511), nullable=True))
        batch_op.add_column(sa.Column('manager', sa.String(length=31), nullable=True))
        batch_op.add_column(sa.Column('size', mysql.DOUBLE(), nullable=True))
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hedge_fund_info', schema=None) as batch_op:
        batch_op.drop_column('stars')
        batch_op.drop_column('size')
        batch_op.drop_column('manager')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
