"""operation

Revision ID: e57aeda0a9d2
Revises: b16ed9f7b134
Create Date: 2021-02-24 14:00:19.788638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57aeda0a9d2'
down_revision = 'b16ed9f7b134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=31), nullable=True),
    sa.Column('action', sa.String(length=31), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('method', sa.String(length=15), nullable=True),
    sa.Column('request_data', sa.TEXT(), nullable=True),
    sa.Column('response_data', sa.TEXT(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    # ### end Alembic commands ###
