"""message

Revision ID: ecec29050d95
Revises: e1b2a107e676
Create Date: 2021-03-22 18:09:33.902874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecec29050d95'
down_revision = 'e1b2a107e676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager_wx_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=127), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager_wx_account', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
