"""pre apply file

Revision ID: f0bcf0d15872
Revises: 9c3a1821c37e
Create Date: 2021-04-16 18:08:33.802041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bcf0d15872'
down_revision = '9c3a1821c37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_apply_file',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rand_str', sa.String(length=127), nullable=True),
    sa.Column('email', sa.String(length=63), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('manager_name', sa.String(length=127), nullable=True),
    sa.Column('manager_id', sa.String(length=31), nullable=True),
    sa.Column('manager_cred_type', sa.String(length=31), nullable=True),
    sa.Column('manager_cred_file', sa.String(length=127), nullable=True),
    sa.Column('manager_cred_no', sa.String(length=127), nullable=True),
    sa.Column('legal_person', sa.String(length=31), nullable=True),
    sa.Column('lp_cred_type', sa.String(length=31), nullable=True),
    sa.Column('lp_cred_file', sa.String(length=127), nullable=True),
    sa.Column('lp_cred_no', sa.String(length=127), nullable=True),
    sa.Column('authorization_file', sa.String(length=127), nullable=True),
    sa.Column('admin_name', sa.String(length=15), nullable=True),
    sa.Column('admin_cred_no', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_apply_file')
    # ### end Alembic commands ###
