"""template

Revision ID: fd367c179767
Revises: 22f3564dc0e3
Create Date: 2021-03-09 10:01:51.599668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd367c179767'
down_revision = '22f3564dc0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_name', sa.String(length=63), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_templates', schema=None) as batch_op:
        batch_op.drop_column('template_name')

    # ### end Alembic commands ###
